# POSTGRES
POSTGRES_USER: postgres
POSTGRES_PASSWORD: postgres
POSTGRES_DB: myblog-dev
# Nest run locally
DB_HOST: localhost
# Nest run in docker, change host to database container name
# DB_HOST: postgres
DB_PORT: 5432
DB_SCHEMA: myblog-dev

# Prisma database connection
# DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DB_HOST}:${DB_PORT}/${POSTGRES_DB}?schema=${DB_SCHEMA}&sslmode=prefer
DATABASE_URL: postgresql://postgres:postgres@localhost:5432/myblog-dev?schema=myblog-dev&sslmode=prefer
